### ISSUE TITLE
Clarify what is bundled

### ISSUE THREAD

**Issue by MarkDBlackwell** [darthdeus/flat-ui-rails#7]
Your [page](https://rubygems.org/gems/flat-ui-rails) on Rubygems says this is "Flat-UI bundled for Rails Asset Pipeline."

By "Flat-UI", are you referring to Designmodo's [Flat UI](http://designmodo.com/flat-free/) Free – PSD&HTML User Interface Kit?

Does this gem bundle that? Or just something similar? Your [Readme](https://github.com/darthdeus/flat-ui-rails/blob/master/README.md) doesn't say. Please add this to the Readme.

For purposes of evangelization, I think it's important to make this clear. For prospective users, knowing what's upstream would facilitate assessing the difficulties you face in maintaining your gem. It would give us a clue to an all-important question: whether your gem will continue to be maintained in future. Don't you think so?

So, how difficult is keeping your gem updated with (the inevitable, eventual) upstream changes?

**Comment by darthdeus** [comment]
I don't have any desire to maintain this gem anymore (#17), which should be apparent just by looking at the commit log.

> By "Flat-UI", are you referring to Designmodo's Flat UI Free – PSD&HTML User Interface Kit? Does this gem bundle that? Or just something similar? Your Readme doesn't say. Please add this to the Readme.

Yes, that's why the name is the same as the original link.

> For purposes of evangelization, I think it's important to make this clear. For prospective users, knowing what's upstream would facilitate assessing the difficulties you face in maintaining your gem. It would give us a clue to an all-important question: whether your gem will continue to be maintained in future. Don't you think so?

This gem contains less than 10 lines of ruby code. It's not that difficult to take a look and see if it's what you need. You are free to make a PR or just create a fork and fix things yourself.

I didn't delete it because there seem to be quite a few people using it.

> So, how difficult is keeping your gem updated with (the inevitable, eventual) upstream changes?

I have over a hundred repositories on Github. If I were to maintain all of them and track upstream changes, I wouldn't be doing anything else.

If you feel this gem isn't being properly maintained, you can either apply to become the new maintainer in #17, or make a PR to fix things.
